# Generated by Django 4.0.2 on 2022-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_photo',
            field=models.BooleanField(default=False),
        ),
    ]
