# Generated by Django 4.0.2 on 2022-03-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_like_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_photo',
        ),
    ]
