# Generated by Django 4.0.2 on 2022-03-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_petphoto_user_likes_alter_petphoto_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='user_likes',
        ),
    ]
